{   'application': True,
    'author': 'OpenEduCat Inc, Odoo Community Association (OCA)',
    'auto_install': False,
    'category': 'Education',
    'complexity': 'easy',
    'data': [   'security/op_security.xml',
                'security/ir.model.access.csv',
                'data/activity_type_data.xml',
                'wizard/student_migrate_wizard_view.xml',
                'views/activity_view.xml',
                'views/activity_type_view.xml',
                'views/student_view.xml',
                'menus/op_menu.xml'],
    'demo': ['demo/activity_demo.xml'],
    'depends': ['openeducat_core'],
    'images': ['static/description/openeducat-activity_banner.jpg'],
    'installable': True,
    'license': 'AGPL-3',
    'name': 'OpenEduCat Activity',
    'sequence': 3,
    'summary': 'Manage Activities',
    'version': '18.0.1.0.0',
    'website': 'https://github.com/OCA/vertical-education'}