{   'application': True,
    'author': 'OpenEduCat Inc, Odoo Community Association (OCA)',
    'auto_install': False,
    'category': 'Education',
    'complexity': 'easy',
    'data': [   'security/op_facility_security.xml',
                'security/ir.model.access.csv',
                'views/facility_view.xml',
                'views/facility_line_view.xml',
                'menus/op_menu.xml'],
    'demo': ['demo/facility_demo.xml'],
    'depends': ['openeducat_core'],
    'images': ['static/description/openeducat-facility_banner.jpg'],
    'installable': True,
    'license': 'AGPL-3',
    'name': 'OpenEduCat Facility',
    'sequence': 3,
    'summary': 'Manage Facility',
    'version': '18.0.1.0.0',
    'website': 'https://github.com/OCA/vertical-education'}