{   'application': True,
    'author': 'OpenEduCat Inc, Odoo Community Association (OCA)',
    'auto_install': False,
    'category': 'Education',
    'complexity': 'easy',
    'data': [   'security/op_classroom_security.xml',
                'security/ir.model.access.csv',
                'views/classroom_view.xml',
                'menus/op_menu.xml'],
    'demo': ['demo/classroom_demo.xml', 'demo/facility_line_demo.xml'],
    'depends': ['openeducat_core', 'openeducat_facility', 'product'],
    'images': ['static/description/openeducat-classroom_banner.jpg'],
    'installable': True,
    'license': 'AGPL-3',
    'name': 'OpenEduCat Classroom',
    'sequence': 3,
    'summary': 'Manage Classroom',
    'version': '18.0.1.0.0',
    'website': 'https://github.com/OCA/vertical-education'}