from . import batch
from . import category
from . import course
from . import faculty
from . import hr
from . import department
from . import res_company
from . import student
from . import subject
from . import subject_registration
from . import res_config_setting
from . import update
from . import student_portal
from . import op_academic_term
from . import op_academic_year
from . import program