{   'application': True,
    'author': 'OpenEduCat Inc, Odoo Community Association (OCA)',
    'auto_install': False,
    'category': 'Education',
    'complexity': 'easy',
    'data': [   'security/op_security.xml',
                'security/ir.model.access.csv',
                'data/attendance_sheet_sequence.xml',
                'wizards/student_attendance_wizard_view.xml',
                'views/attendance_register_view.xml',
                'views/attendance_sheet_view.xml',
                'views/attendance_line_view.xml',
                'views/attendance_type_view.xml',
                'views/attendance_session_view.xml',
                'views/student_view.xml',
                'report/student_attendance_report.xml',
                'report/report_menu.xml',
                'menus/op_menu.xml'],
    'demo': [   'demo/attendance_register_demo.xml',
                'demo/attendance_sheet_demo.xml',
                'demo/attendance_line_demo.xml',
                'demo/attendance_type_demo.xml'],
    'depends': ['openeducat_timetable'],
    'images': ['static/description/openeducat-attendance_banner.jpg'],
    'installable': True,
    'license': 'AGPL-3',
    'name': 'OpenEduCat Attendance',
    'sequence': 3,
    'summary': 'Manage Attendances',
    'version': '18.0.1.0.0',
    'website': 'https://github.com/OCA/vertical-education'}