{   'application': True,
    'author': 'OpenEduCat Inc, Odoo Community Association (OCA)',
    'auto_install': False,
    'category': 'Education',
    'complexity': 'easy',
    'data': [   'security/op_security.xml',
                'security/ir.model.access.csv',
                'views/timetable_view.xml',
                'views/timing_view.xml',
                'views/faculty_view.xml',
                'views/res_config_setting_view.xml',
                'report/report_timetable_student_generate.xml',
                'report/report_timetable_teacher_generate.xml',
                'report/report_menu.xml',
                'wizard/generate_timetable_view.xml',
                'wizard/time_table_report.xml',
                'wizard/session_confirmation.xml',
                'views/timetable_templates.xml',
                'menus/op_menu.xml'],
    'demo': ['demo/timing_demo.xml', 'demo/op_timetable_demo.xml'],
    'depends': ['openeducat_classroom'],
    'images': ['static/description/openeducat-timetable_banner.jpg'],
    'installable': True,
    'license': 'AGPL-3',
    'name': 'OpenEduCat Timetable',
    'sequence': 3,
    'summary': 'Manage TimeTables',
    'version': '18.0.1.0.0',
    'website': 'https://github.com/OCA/vertical-education'}