{   'application': True,
    'author': 'OpenEduCat Inc, Odoo Community Association (OCA)',
    'auto_install': False,
    'category': 'Education',
    'complexity': 'easy',
    'depends': [   'openeducat_admission',
                   'openeducat_assignment',
                   'openeducat_attendance',
                   'openeducat_library',
                   'openeducat_parent',
                   'openeducat_exam'],
    'images': ['static/description/openeducat-erp_banner.jpg'],
    'installable': True,
    'license': 'AGPL-3',
    'name': 'OpenEduCat ERP',
    'sequence': 3,
    'summary': 'Manage Students, Faculties and Education Institute',
    'version': '18.0.1.0.0',
    'website': 'https://github.com/OCA/vertical-education'}