{   'application': True,
    'author': 'OpenEduCat Inc, Odoo Community Association (OCA)',
    'auto_install': False,
    'category': 'Education',
    'complexity': 'easy',
    'data': [   'security/op_admission_security.xml',
                'security/ir.model.access.csv',
                'data/admission_sequence.xml',
                'data/parameter_data.xml',
                'views/admission_register_view.xml',
                'views/admission_view.xml',
                'report/report_admission_analysis.xml',
                'report/report_menu.xml',
                'wizard/admission_analysis_wizard_view.xml',
                'menus/op_menu.xml'],
    'demo': ['demo/admission_register_demo.xml', 'demo/admission_demo.xml'],
    'depends': ['openeducat_core', 'openeducat_fees'],
    'images': ['static/description/openeducat-admission_banner.jpg'],
    'installable': True,
    'license': 'AGPL-3',
    'name': 'OpenEduCat Admission',
    'sequence': 3,
    'summary': 'Manage Admissions',
    'test': [],
    'version': '18.0.1.0.0',
    'website': 'https://github.com/OCA/vertical-education'}