{   'application': True,
    'author': 'OpenEduCat Inc, Odoo Community Association (OCA)',
    'auto_install': False,
    'category': 'Education',
    'complexity': 'easy',
    'data': [   'security/op_security.xml',
                'security/ir.model.access.csv',
                'views/res_partner_view.xml',
                'views/exam_attendees_view.xml',
                'views/exam_room_view.xml',
                'views/exam_session_view.xml',
                'views/exam_type_view.xml',
                'wizard/room_distribution_view.xml',
                'wizard/held_exam_view.xml',
                'views/exam_view.xml',
                'views/marksheet_line_view.xml',
                'views/marksheet_register_view.xml',
                'views/grade_configuration_view.xml',
                'views/result_line_view.xml',
                'views/result_template_view.xml',
                'report/report_ticket.xml',
                'report/student_marksheet.xml',
                'report/report_menu.xml',
                'menus/op_menu.xml'],
    'demo': [   'demo/exam_room_demo.xml',
                'demo/exam_type_demo.xml',
                'demo/exam_session_demo.xml',
                'demo/exam_demo.xml',
                'demo/exam_attendees_demo.xml',
                'demo/grade_configuration_demo.xml',
                'demo/result_template_demo.xml',
                'demo/marksheet_register_demo.xml',
                'demo/marksheet_line_demo.xml',
                'demo/result_line_demo.xml'],
    'depends': ['openeducat_classroom'],
    'images': ['static/description/openeducat-exam_banner.jpg'],
    'installable': True,
    'license': 'AGPL-3',
    'name': 'OpenEduCat Exam',
    'sequence': 3,
    'summary': 'Manage Exam',
    'version': '18.0.1.0.0',
    'website': 'https://github.com/OCA/vertical-education'}