{   'application': True,
    'assets': {   'web._assets_primary_variables': [   '/web_openeducat/static/src/scss/primary_variables.scss'],
                  'web.assets_frontend': ['/web_openeducat/static/src/scss/homepage.scss']},
    'author': 'OpenEduCat Inc, Odoo Community Association (OCA)',
    'category': 'Website',
    'data': [   'views/assets.xml',
                'views/snippets/slider.xml',
                'views/snippets/about-us.xml',
                'views/snippets/ourcourse.xml',
                'views/snippets/achievement.xml',
                'views/snippets/teacher.xml',
                'views/snippets/event.xml',
                'views/snippets/newsfeed.xml',
                'views/snippets/footer.xml',
                'views/image_library.xml'],
    'demo': ['data/homepage_demo.xml', 'data/footer_template.xml'],
    'depends': ['website'],
    'images': ['static/description/web_openeducat_banner.jpg'],
    'license': 'AGPL-3',
    'name': 'Web OpenEduCat',
    'qweb': ['static/src/xml/base_inherit.xml'],
    'sequence': 3,
    'version': '18.0.1.0.0',
    'website': 'https://github.com/OCA/vertical-education'}