{   'application': True,
    'assets': {   'web.assets_backend': [   'openeducat_fees/static/src/js/page_list.js',
                                            'openeducat_fees/static/src/js/fees_term_widget.js',
                                            'openeducat_fees/static/src/xml/fees_term_widget_template.xml']},
    'author': 'OpenEduCat Inc, Odoo Community Association (OCA)',
    'auto_install': False,
    'category': 'Education',
    'complexity': 'easy',
    'data': [   'security/op_security.xml',
                'security/ir.model.access.csv',
                'report/report_menu.xml',
                'report/fees_analysis_report_view.xml',
                'wizard/fees_detail_report_wizard_view.xml',
                'wizard/select_term_type.xml',
                'views/fees_terms_view.xml',
                'views/student_view.xml',
                'views/course_view.xml',
                'views/fees_element_view.xml'],
    'demo': [   'demo/product_category_demo.xml',
                'demo/product_demo.xml',
                'demo/fees_element_line_demo.xml',
                'demo/fees_terms_line_demo.xml',
                'demo/fees_terms_demo.xml',
                'demo/course_demo.xml',
                'demo/student_fees_details_demo.xml'],
    'depends': ['openeducat_core', 'account'],
    'images': ['static/description/openeducat-fees_banner.jpg'],
    'installable': True,
    'license': 'AGPL-3',
    'name': 'OpenEduCat Fees',
    'sequence': 3,
    'summary': 'Manage Fees',
    'version': '18.0.1.0.0',
    'website': 'https://github.com/OCA/vertical-education'}