{   'application': True,
    'author': 'OpenEduCat Inc, Odoo Community Association (OCA)',
    'auto_install': False,
    'category': 'Education',
    'complexity': 'easy',
    'data': [   'security/op_security.xml',
                'security/ir.model.access.csv',
                'data/parent_user_data.xml',
                'views/parent_view.xml',
                'views/parent_relationship_view.xml',
                'menus/op_menu.xml',
                'report/report_student_bonafide_inherit.xml'],
    'demo': [   'demo/res_partner_demo.xml',
                'demo/res_users_demo.xml',
                'demo/parent_relationship_demo.xml',
                'demo/parent_demo.xml'],
    'depends': ['openeducat_core'],
    'images': ['static/description/openeducat-parent_banner.jpg'],
    'installable': True,
    'license': 'AGPL-3',
    'name': 'OpenEduCat Parent',
    'sequence': 3,
    'summary': 'Manage Parent',
    'version': '18.0.1.0.0',
    'website': 'https://github.com/OCA/vertical-education'}