{   'application': True,
    'author': 'OpenEduCat Inc, Odoo Community Association (OCA)',
    'auto_install': False,
    'category': 'Education',
    'complexity': 'easy',
    'data': [   'security/op_security.xml',
                'security/ir.model.access.csv',
                'views/assignment_view.xml',
                'views/assignment_type_view.xml',
                'views/assignment_sub_line_view.xml',
                'views/student_view.xml',
                'data/action_rule_data.xml',
                'menus/op_menu.xml'],
    'demo': [   'demo/assignment_type_demo.xml',
                'demo/assignment_demo.xml',
                'demo/assignment_sub_line_demo.xml'],
    'depends': ['base_automation', 'openeducat_core'],
    'images': ['static/description/openeducat-assignment_banner.jpg'],
    'installable': True,
    'license': 'AGPL-3',
    'name': 'OpenEduCat Assignment',
    'sequence': 3,
    'summary': 'Manage Assgiments',
    'version': '18.0.1.0.0',
    'website': 'https://github.com/OCA/vertical-education'}